import { OPERATIONAL_EVENT_TYPES } from "@/lib/operations/operationalEventTypes";
import { PLATFORM_EVENT_SUBTYPE } from "@/lib/platform/events/taxonomy";
import type { PlatformEventCategory } from "@/lib/platform/events/taxonomy";

/**
 * Canonical failure `OperationalActivityEvent.type` values surfaced in Operations → Failures.
 * Sourced from real `emitPlatformEvent` / `emitOperationalEvent` instrumentation — not aspirational names.
 *
 * Retention: ops events are queryable here for ~90 days (policy; no purge cron yet).
 */
export const OPERATIONAL_FAILURE_TYPES = [
  /** Legacy Square terminal path — `emitPaymentTerminalEvent` */
  OPERATIONAL_EVENT_TYPES.PAYMENT_FAILED,
  PLATFORM_EVENT_SUBTYPE.PAYMENT_WEBHOOK_PROCESSING_FAILED,
  PLATFORM_EVENT_SUBTYPE.PAYMENT_SQUARE_ORPHAN_WEBHOOK,
  PLATFORM_EVENT_SUBTYPE.PAYMENT_REGISTER_FAILED,
  PLATFORM_EVENT_SUBTYPE.SHIPMENT_QUOTE_FAILED,
  PLATFORM_EVENT_SUBTYPE.SHIPMENT_LABEL_FAILED,
  PLATFORM_EVENT_SUBTYPE.SHIPMENT_WEBHOOK_PROCESSING_FAILED,
  PLATFORM_EVENT_SUBTYPE.SHIPMENT_WEBHOOK_ORPHAN,
  PLATFORM_EVENT_SUBTYPE.AUTH_LOGIN_FAILED,
  PLATFORM_EVENT_SUBTYPE.SYSTEM_INTEGRATION_DEGRADED,
  PLATFORM_EVENT_SUBTYPE.ORDER_DRAFT_CREATE_FAILED,
  PLATFORM_EVENT_SUBTYPE.MENU_SYNC_FAILED,
  /** Notification delivery — outbound/inbound email subsystem */
  PLATFORM_EVENT_SUBTYPE.SYSTEM_EMAIL_SEND_FAILED,
  PLATFORM_EVENT_SUBTYPE.SYSTEM_EMAIL_INBOUND_FAILED,
  PLATFORM_EVENT_SUBTYPE.SECURITY_WEBHOOK_SIGNATURE_INVALID,
  OPERATIONAL_EVENT_TYPES.CATERING_INQUIRY_FAILED,
] as const;

export type OperationalFailureType = (typeof OPERATIONAL_FAILURE_TYPES)[number];

export const OPERATIONAL_FAILURE_TYPE_SET = new Set<string>(OPERATIONAL_FAILURE_TYPES);

export function isOperationalFailureType(type: string): type is OperationalFailureType {
  return OPERATIONAL_FAILURE_TYPE_SET.has(type);
}

/** UI grouping — maps subtype → platform category (fallback when envelope missing). */
export const FAILURE_TYPE_CATEGORY: Record<OperationalFailureType, PlatformEventCategory> = {
  [OPERATIONAL_EVENT_TYPES.PAYMENT_FAILED]: "PAYMENT_EVENT",
  [PLATFORM_EVENT_SUBTYPE.PAYMENT_WEBHOOK_PROCESSING_FAILED]: "PAYMENT_EVENT",
  [PLATFORM_EVENT_SUBTYPE.PAYMENT_SQUARE_ORPHAN_WEBHOOK]: "PAYMENT_EVENT",
  [PLATFORM_EVENT_SUBTYPE.PAYMENT_REGISTER_FAILED]: "PAYMENT_EVENT",
  [PLATFORM_EVENT_SUBTYPE.SHIPMENT_QUOTE_FAILED]: "SHIPMENT_EVENT",
  [PLATFORM_EVENT_SUBTYPE.SHIPMENT_LABEL_FAILED]: "SHIPMENT_EVENT",
  [PLATFORM_EVENT_SUBTYPE.SHIPMENT_WEBHOOK_PROCESSING_FAILED]: "SHIPMENT_EVENT",
  [PLATFORM_EVENT_SUBTYPE.SHIPMENT_WEBHOOK_ORPHAN]: "SHIPMENT_EVENT",
  [PLATFORM_EVENT_SUBTYPE.AUTH_LOGIN_FAILED]: "AUTH_EVENT",
  [PLATFORM_EVENT_SUBTYPE.SYSTEM_INTEGRATION_DEGRADED]: "SYSTEM_EVENT",
  [PLATFORM_EVENT_SUBTYPE.ORDER_DRAFT_CREATE_FAILED]: "ORDER_EVENT",
  [PLATFORM_EVENT_SUBTYPE.MENU_SYNC_FAILED]: "MENU_EVENT",
  [PLATFORM_EVENT_SUBTYPE.SYSTEM_EMAIL_SEND_FAILED]: "SYSTEM_EVENT",
  [PLATFORM_EVENT_SUBTYPE.SYSTEM_EMAIL_INBOUND_FAILED]: "SYSTEM_EVENT",
  [PLATFORM_EVENT_SUBTYPE.SECURITY_WEBHOOK_SIGNATURE_INVALID]: "SECURITY_EVENT",
  [OPERATIONAL_EVENT_TYPES.CATERING_INQUIRY_FAILED]: "ORDER_EVENT",
};

export const FAILURE_SUBTYPE_LABELS: Record<OperationalFailureType, string> = {
  [OPERATIONAL_EVENT_TYPES.PAYMENT_FAILED]: "Payment failed",
  [PLATFORM_EVENT_SUBTYPE.PAYMENT_WEBHOOK_PROCESSING_FAILED]: "Webhook processing failed",
  [PLATFORM_EVENT_SUBTYPE.PAYMENT_SQUARE_ORPHAN_WEBHOOK]: "Orphan Square webhook",
  [PLATFORM_EVENT_SUBTYPE.PAYMENT_REGISTER_FAILED]: "Payment registration failed",
  [PLATFORM_EVENT_SUBTYPE.SHIPMENT_QUOTE_FAILED]: "Shipping quote failed",
  [PLATFORM_EVENT_SUBTYPE.SHIPMENT_LABEL_FAILED]: "Label purchase failed",
  [PLATFORM_EVENT_SUBTYPE.SHIPMENT_WEBHOOK_PROCESSING_FAILED]: "Shipment webhook processing failed",
  [PLATFORM_EVENT_SUBTYPE.SHIPMENT_WEBHOOK_ORPHAN]: "Orphan shipment webhook",
  [PLATFORM_EVENT_SUBTYPE.AUTH_LOGIN_FAILED]: "Login failed",
  [PLATFORM_EVENT_SUBTYPE.SYSTEM_INTEGRATION_DEGRADED]: "Integration degraded",
  [PLATFORM_EVENT_SUBTYPE.ORDER_DRAFT_CREATE_FAILED]: "Draft order create failed",
  [PLATFORM_EVENT_SUBTYPE.MENU_SYNC_FAILED]: "Menu sync failed",
  [PLATFORM_EVENT_SUBTYPE.SYSTEM_EMAIL_SEND_FAILED]: "Email send failed",
  [PLATFORM_EVENT_SUBTYPE.SYSTEM_EMAIL_INBOUND_FAILED]: "Inbound email failed",
  [PLATFORM_EVENT_SUBTYPE.SECURITY_WEBHOOK_SIGNATURE_INVALID]: "Invalid webhook signature",
  [OPERATIONAL_EVENT_TYPES.CATERING_INQUIRY_FAILED]: "Catering inquiry failed",
};
