import type { MerchProduct } from "@/types/merch";
import { fulfillmentForSlug } from "@/lib/merch/fulfillment";

/**
 * Mock catalog — replace with Square Catalog (Store category) fetch via `/api/store/catalog`.
 */
export const merchCatalog: MerchProduct[] = [
  {
    id: "tee-classic",
    squareCatalogItemId: undefined,
    name: "Bridge Logo Tee",
    subtitle: "Heavyweight cotton",
    description:
      "Structured tee with embroidered bridge mark. Unisex fit — wears like your favorite diner tee.",
    collectionId: "apparel",
    featuredCollectionIds: ["apparel"],
    price: 28,
    compareAtPrice: 34,
    imageFallbackKey: "teal",
    badges: ["New"],
    inventory: "in_stock",
    fulfillment: fulfillmentForSlug("standard_pickup"),
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: [
      { id: "cream", label: "Natural", hex: "#F5F0E8" },
      { id: "charcoal", label: "Charcoal", hex: "#2C2C2C" },
    ],
    buttonLabel: "Choose options",
  },
  {
    id: "hoodie-teal",
    name: "Momo's Pullover Hoodie",
    subtitle: "Teal colorway",
    description: "Midweight fleece, wordmark across the back. Built for Bay mornings.",
    collectionId: "hoodies",
    featuredCollectionIds: ["hoodies", "apparel"],
    price: 52,
    imageFallbackKey: "charcoal",
    badges: ["Staff pick"],
    inventory: "low_stock",
    fulfillment: fulfillmentForSlug("standard_pickup"),
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: [{ id: "teal", label: "Teal", hex: "#4A8B8C" }],
    buttonLabel: "Choose options",
  },
  {
    id: "hat-snapback",
    name: "Bridge Snapback",
    subtitle: "Adjustable",
    description: "Embroidered Carquinez Bridge. One size — dialed fit.",
    collectionId: "hats",
    featuredCollectionIds: ["hats"],
    price: 32,
    imageFallbackKey: "gold",
    inventory: "in_stock",
    fulfillment: fulfillmentForSlug("standard_pickup"),
    colors: [{ id: "blk", label: "Black" }, { id: "cream", label: "Natural", hex: "#F5F0E8" }],
    buttonLabel: "Choose options",
  },
  {
    id: "mug-cafe",
    name: "Café de Olla Mug",
    subtitle: "12oz ceramic",
    description: "Microwave & dishwasher safe. Gloss glaze with Momo's mark.",
    collectionId: "drinkware",
    featuredCollectionIds: ["drinkware"],
    price: 16,
    imageFallbackKey: "cream",
    inventory: "in_stock",
    fulfillment: fulfillmentForSlug("standard_pickup"),
    buttonLabel: "Add to bag",
  },
  {
    id: "tote-canvas",
    name: "Market Tote",
    subtitle: "Heavy canvas",
    description: "Natural canvas, wide straps — farmers market tested.",
    collectionId: "accessories",
    price: 18,
    imageFallbackKey: "teal",
    inventory: "in_stock",
    fulfillment: fulfillmentForSlug("standard_pickup"),
    buttonLabel: "Add to bag",
  },
  {
    id: "gift-card",
    name: "Momo's Gift Card",
    subtitle: "Breakfast budget",
    description: "Load for someone who lives for our plates. Redeem in Vallejo.",
    collectionId: "gift_cards",
    featuredCollectionIds: ["gift_cards"],
    price: 10,
    priceLabel: "From $10",
    imageFallbackKey: "gold",
    badges: ["Popular"],
    inventory: "in_stock",
    fulfillment: fulfillmentForSlug("gift_card"),
    amountOptions: [10, 25, 50, 100],
    buttonLabel: "Choose options",
  },
];
